---

- name: Check for homebrew.
  command: stat /usr/local/bin/brew
  register: stat_homebrew
  ignore_errors: True

- name: Install package.
  homebrew: name=git state=present
  when: stat_homebrew.rc == 0
