---
- name: Installing Zsh and git
  apt: pkg=zsh,git state=latest
  register: installation

- name: Delete existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then rm ~/.zshrc; fi
  when: installation|success
  sudo: no

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Linking ~/.zshrc
  file:
    src: /config/zsh/.zshrc
    dest: /home/{{ user_name }}/.zshrc
    state: link
  when: cloning|success
  sudo: yes
