---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: mysql
  roles:
    - mysql

- hosts: redis
  roles:
    - redis


- hosts: application
  handlers:
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

