---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: mysql
  roles:
    - mysql

- hosts: redis
  roles:
    - redis

- hosts: utility
  vars:
    nodejs_npm_global_packages:
      - name: jslint
      - name: node-sass
  roles:
    - nodejs

- hosts: ci-server
  roles:
    - jenkins

- hosts: servers
  vars:
    manala_phantomjs_config:
      - webdriver:          4444
      - webdriver-logfile:  /var/log/phantomjs.log
      - webdriver-loglevel: DEBUG
  roles:
    - role: phantomjs

- hosts: application
  handlers:
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

- hosts: all
  remote_user: root
  vars:
    __users__:
      vagrant:
        zsh_default_shell: Yes
        zsh_prompt_install: Yes
        zsh_prompt_name: pure
        zsh_prompt_download_url: https://raw.githubusercontent.com/sindresorhus/pure/master/pure.zsh
        zsh_prompt_additional_url: https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh
        zfunctions_directory: ./files/zfunctions
        zshrc_content: |
          alias ls='ls -lah'
  roles:
    - zsh

- hosts: all
  roles:
    - ohmyzsh
